version: '2'
services:
  rethinkdb:
    image: rethinkdb
    ports:
      - "localhost:8080:8080"
  util:
    build: ./modules/util
    command: sh -c 'nodemon seneca_config.coffee'
    volumes:
      - ./modules/util/:/usr/microserv/util/
      - /usr/microserv/util/node_modules/
    expose:
      - 10101
    links:
      - rethinkdb

  db:
    build: ./modules/db
    command: sh -c 'nodemon seneca_config.coffee'
    volumes:
      - ./modules/db:/usr/microserv/db/
      - /usr/microserv/db/node_modules/
    expose:
      - 10101
    links:
      - util
      - rethinkdb

  todo:
    build: ./modules/todo
    command: sh -c 'nodemon seneca_config.coffee'
    volumes:
      - ./modules/todo:/usr/microserv/todo/
      - /usr/microserv/todo/node_modules/
    expose:
      - 10101
    links:
      - util
      - db

  web:
    build: ./modules/web
    command: sh -c 'nodemon server.coffee'
    volumes:
      - ./modules/web/:/usr/microserv/web/
      - /usr/microserv/web/node_modules/
    expose:
      - 10101
      - 9999
    ports:
      - "localhost:9999:9999"
    links:
      - util
      - db
      - todo
