require('angular').module 'todoApp'
  .service 'todoService', require './todoService'
  .service 'authService', require './authService'
  .service 'userService', require './userService'
  .service 'crudService', require './crudService'
